from typing import Any, Optional

class Primadb:
    def __init__(self, replica_id: Optional[str] = ...) -> None: ...
    def replica_id(self) -> str: ...
    def chain(self, root: str) -> Chain: ...
    def snapshot(self) -> Any: ...
    def snapshot_for_root(self, root: Optional[str] = ...) -> Any: ...
    def export_snapshot_json(self) -> str: ...
    def import_snapshot_json(self, payload: str) -> None: ...
    def merge_snapshot_json(self, payload: str) -> None: ...
    def pending_operations(self) -> Any: ...
    def pending_envelope(self) -> Any: ...
    def export_pending_operations_json(self) -> str: ...
    def drain_pending_operations(self) -> Any: ...
    def drain_pending_envelope(self) -> Any: ...
    def apply_operations(self, operations: Any) -> int: ...
    def apply_envelope(self, envelope: Any) -> int: ...
    def apply_operations_json(self, payload: str) -> int: ...
    def open_durable_storage(self, config: Any) -> Any: ...
    def connect_relay(self, config: Any) -> WebSocketSync: ...
    def connect_mesh(self, config: Any) -> WebRtcMesh: ...

class Chain:
    def field(self, key: str) -> Chain: ...
    def path(self) -> str: ...
    def put(self, value: Any) -> None: ...
    def put_signed(self, value: Any, certificate: Optional[str] = ...) -> None: ...
    def once(self) -> Any: ...
    def unset(self) -> None: ...
    def set(self, value: Any) -> str: ...
    def set_signed(self, value: Any, certificate: Optional[str] = ...) -> str: ...
    def remove(self, value: Any) -> str: ...
    def map(self) -> Any: ...
    def query(self, spec: Any) -> Any: ...
    def first_query(self, spec: Any) -> Any: ...
    def scan(self, spec: Any) -> Any: ...
    def subscribe(self) -> Subscription: ...

class Subscription:
    def next(self) -> Any: ...
    def try_next(self) -> Any: ...
    def close(self) -> None: ...

class WebSocketSync:
    def is_connected(self) -> bool: ...
    def pending_count(self) -> int: ...
    def inflight_count(self) -> int: ...
    def known_peer_count(self) -> int: ...
    def recommended_peers(self) -> Any: ...
    def remote_get(self, peer_id: str, path: Any) -> Any: ...
    def remote_query(self, peer_id: str, path: Any, spec: Any) -> Any: ...
    def remote_lex(self, peer_id: str, path: Any, spec: Any) -> Any: ...
    def remote_snapshot(self, peer_id: str, root: Optional[str] = ...) -> Any: ...
    def flush_pending(self) -> int: ...
    def retry_inflight(self) -> int: ...
    def close(self) -> None: ...

class WebRtcMesh:
    def peer_id(self) -> str: ...
    def signaling_mode(self) -> str: ...
    def relay_url(self) -> Optional[str]: ...
    def relay_connected(self) -> bool: ...
    def peer_count(self) -> int: ...
    def open_peer_count(self) -> int: ...
    def inflight_count(self) -> int: ...
    def recommended_peers(self) -> Any: ...
    def flush_pending(self) -> int: ...
    def retry_inflight(self) -> int: ...
    def close(self) -> None: ...
