from dataclasses import dataclass
from typing import Any, Optional, Protocol, TypedDict

class PresenceIdentity(TypedDict, total=False):
    publicKey: str
    alias: Optional[str]
    keyScheme: str
    sessionId: str
    claims: dict[str, str]
    issuedAtMillis: int
    expiresAtMillis: Optional[int]

class VerifiedIdentity(TypedDict, total=False):
    publicKey: str
    alias: Optional[str]
    peerId: str
    replicaId: str
    transport: str
    sessionId: str
    claims: dict[str, str]
    issuedAtMillis: int
    expiresAtMillis: Optional[int]
    trust: str

class IdentityKeyPair(TypedDict):
    publicKey: str
    secretKey: str

class UserGrant(TypedDict, total=False):
    root: str
    read: bool
    write: bool

class PeerHookContext(TypedDict, total=False):
    peerId: str
    replicaId: str
    transport: str
    identity: Optional[PresenceIdentity]
    capabilities: list[str]
    topics: list[str]
    metadata: dict[str, str]

class ConnectHookContext(TypedDict, total=False):
    peer: PeerHookContext
    transport: str
    relayUrl: Optional[str]
    verifiedIdentity: Optional[VerifiedIdentity]

class RoomHookContext(TypedDict, total=False):
    peerId: str
    room: str
    transport: str
    peer: Optional[PeerHookContext]
    verifiedIdentity: Optional[VerifiedIdentity]

class ServeRequestContext(TypedDict, total=False):
    peerId: str
    transport: str
    requestId: Optional[str]
    watchId: Optional[str]
    request: Any
    verifiedIdentity: Optional[VerifiedIdentity]

class ServeResultContext(TypedDict, total=False):
    peerId: str
    transport: str
    requestId: Optional[str]
    watchId: Optional[str]
    request: Any
    initial: bool
    verifiedIdentity: Optional[VerifiedIdentity]

class SessionAuthConfig(TypedDict, total=False):
    requireAuthenticatedPeers: bool
    trustedPublicKeys: list[str]
    trustedAliases: list[str]
    challengeTimeoutMs: int
    sessionTtlMs: int
    allowUnauthenticatedPresence: bool

class RelayClientConfig(TypedDict, total=False):
    url: str
    retryIntervalMs: int
    sessionAuth: SessionAuthConfig

class IceServerConfig(TypedDict, total=False):
    urls: str | list[str]
    username: Optional[str]
    credential: Optional[str]

class MeshConfig(TypedDict, total=False):
    room: str
    signaling: str
    relayUrl: Optional[str]
    retryIntervalMs: int
    iceServers: list[IceServerConfig]
    sessionAuth: SessionAuthConfig

class NetworkHooks(Protocol):
    def on_connect(self, context: ConnectHookContext, /) -> Any: ...
    def on_join_room(self, context: RoomHookContext, /) -> Any: ...
    def on_pull(self, context: ServeRequestContext, /) -> Any: ...
    def on_watch(self, context: ServeRequestContext, /) -> Any: ...
    def on_serve_result(self, context: ServeResultContext, result: Any, /) -> Any: ...

class Primadb:
    def __init__(self, replica_id: Optional[str] = ...) -> None: ...
    def replica_id(self) -> str: ...
    def chain(self, root: str) -> Chain: ...
    def scope(self, root: str) -> Scope: ...
    def transaction(self, steps: Any) -> Any: ...
    def snapshot(self) -> Any: ...
    def snapshot_for_root(self, root: Optional[str] = ...) -> Any: ...
    def node_state(self, id: str) -> Any: ...
    def apply_node_state(self, node: Any) -> bool: ...
    def export_snapshot_json(self) -> str: ...
    def import_snapshot_json(self, payload: str) -> None: ...
    def merge_snapshot_json(self, payload: str) -> None: ...
    def pending_operations(self) -> Any: ...
    def pending_envelope(self) -> Any: ...
    def export_pending_operations_json(self) -> str: ...
    def drain_pending_operations(self) -> Any: ...
    def drain_pending_envelope(self) -> Any: ...
    def drain_pending_envelope_json(self) -> str: ...
    def apply_operations(self, operations: Any) -> int: ...
    def apply_envelope(self, envelope: Any) -> int: ...
    def apply_operations_json(self, payload: str) -> int: ...
    def open_durable_storage(self, config: Any) -> Any: ...
    def open_blob_storage(self, config: Any) -> Any: ...
    def register_user(self, alias: str, public_key: str, grants: list[UserGrant]) -> None: ...
    def authenticate_local_user(self, alias: str, secret_key: str, grants: list[UserGrant]) -> None: ...
    def set_require_signed_sync(self, required: bool) -> None: ...
    def connect_relay(self, config: RelayClientConfig | dict[str, Any]) -> WebSocketSync: ...
    def connect_mesh(self, config: MeshConfig | dict[str, Any]) -> WebRtcMesh: ...
    def set_network_hooks(self, hooks: NetworkHooks | dict[str, Any] | object | None) -> None: ...
    def clear_network_hooks(self) -> None: ...

def generate_identity() -> IdentityKeyPair: ...

class Scope:
    def root(self) -> str: ...
    def configure(self, policy: Any) -> None: ...
    def policy(self) -> Any: ...
    def proposals(self) -> Any: ...
    def transaction(self, steps: Any, options: Optional[Any] = ...) -> Any: ...

@dataclass
class PrimadbMoqFrame:
    path: str
    track: str
    sequence: int
    payload: bytes
    def json(self) -> Any: ...

class PrimadbMoqSession:
    db: Any
    path: str
    track: str
    def __init__(self, db: Any, *, path: str, track: str = ...) -> None: ...
    def subscribe_from(self, publisher: PrimadbMoqSession) -> None: ...
    def flush_pending(self) -> int: ...
    def receive_frame(self, frame: PrimadbMoqFrame) -> int: ...
    def close(self) -> None: ...

class PrimadbMoqLoopback:
    publisher: PrimadbMoqSession
    subscriber: PrimadbMoqSession
    def __init__(self, publisher: PrimadbMoqSession, subscriber: PrimadbMoqSession) -> None: ...
    def flush(self) -> int: ...
    def close(self) -> None: ...

def create_primadb_moq_loopback(
    *,
    publisher_db: Any,
    subscriber_db: Any,
    path: str,
    track: str = ...,
) -> PrimadbMoqLoopback: ...

class Chain:
    def field(self, key: str) -> Chain: ...
    def path(self) -> str: ...
    def put(self, value: Any) -> None: ...
    def put_bytes(self, value: bytes) -> None: ...
    def put_signed(self, value: Any, certificate: Optional[str] = ...) -> None: ...
    def once(self) -> Any: ...
    def once_bytes(self) -> Optional[bytes]: ...
    def unset(self) -> None: ...
    def set(self, value: Any) -> str: ...
    def set_signed(self, value: Any, certificate: Optional[str] = ...) -> str: ...
    def remove(self, value: Any) -> str: ...
    def put_blob(self, value: bytes, media_type: Optional[str] = ...) -> Any: ...
    def blob_ref(self) -> Any: ...
    def get_blob(self) -> Optional[bytes]: ...
    def map(self) -> Any: ...
    def query(self, spec: Any) -> Any: ...
    def first_query(self, spec: Any) -> Any: ...
    def scan(self, spec: Any) -> Any: ...
    def traverse(self, spec: Any) -> Any: ...
    def subscribe(self) -> Subscription: ...
    def watch_traverse(self, spec: Any) -> TraversalSubscription: ...

class Subscription:
    def next(self) -> Any: ...
    def try_next(self) -> Any: ...
    def close(self) -> None: ...

class TraversalSubscription:
    def next(self) -> Any: ...
    def try_next(self) -> Any: ...
    def close(self) -> None: ...

class RelayServer:
    @staticmethod
    def listen(config: Any) -> RelayServer: ...
    def bind_addr(self) -> str: ...
    def url(self) -> str: ...
    def client_count(self) -> int: ...
    def peer_count(self) -> int: ...
    def close(self) -> None: ...

class RemoteWatch:
    def next(self) -> Any: ...
    def try_next(self) -> Any: ...
    def close(self) -> None: ...

class WebSocketSync:
    def is_connected(self) -> bool: ...
    def pending_count(self) -> int: ...
    def inflight_count(self) -> int: ...
    def known_peer_count(self) -> int: ...
    def recommended_peers(self) -> Any: ...
    def remote_get(self, peer_id: str, path: Any) -> Any: ...
    def remote_query(self, peer_id: str, path: Any, spec: Any) -> Any: ...
    def remote_lex(self, peer_id: str, path: Any, spec: Any) -> Any: ...
    def remote_node(self, peer_id: str, id: str) -> Any: ...
    def remote_snapshot(self, peer_id: str, root: Optional[str] = ...) -> Any: ...
    def remote_transaction(
        self,
        peer_id: str,
        scope: str,
        steps: Any,
        options: Optional[Any] = ...,
    ) -> Any: ...
    def watch_remote_get(self, peer_id: str, path: Any) -> RemoteWatch: ...
    def watch_remote_map(self, peer_id: str, path: Any) -> RemoteWatch: ...
    def watch_remote_query(self, peer_id: str, path: Any, spec: Any) -> RemoteWatch: ...
    def watch_remote_lex(self, peer_id: str, path: Any, spec: Any) -> RemoteWatch: ...
    def watch_remote_node(self, peer_id: str, id: str) -> RemoteWatch: ...
    def watch_remote_snapshot(self, peer_id: str, root: Optional[str] = ...) -> RemoteWatch: ...
    def flush_pending(self) -> int: ...
    def retry_inflight(self) -> int: ...
    def close(self) -> None: ...

class WebRtcMesh:
    def peer_id(self) -> str: ...
    def signaling_mode(self) -> str: ...
    def relay_url(self) -> Optional[str]: ...
    def relay_connected(self) -> bool: ...
    def peer_count(self) -> int: ...
    def open_peer_count(self) -> int: ...
    def inflight_count(self) -> int: ...
    def recommended_peers(self) -> Any: ...
    def watch_remote_get(self, peer_id: str, path: Any) -> RemoteWatch: ...
    def watch_remote_map(self, peer_id: str, path: Any) -> RemoteWatch: ...
    def watch_remote_query(self, peer_id: str, path: Any, spec: Any) -> RemoteWatch: ...
    def watch_remote_lex(self, peer_id: str, path: Any, spec: Any) -> RemoteWatch: ...
    def watch_remote_node(self, peer_id: str, id: str) -> RemoteWatch: ...
    def watch_remote_snapshot(self, peer_id: str, root: Optional[str] = ...) -> RemoteWatch: ...
    def flush_pending(self) -> int: ...
    def retry_inflight(self) -> int: ...
    def close(self) -> None: ...
